DESCRIPTION
cleanup
configure
src/Makevars.in

This address part of the discussion in #33 and I have tested it on 32 and 64 bit Linux. In both cases the system-wide `libblpapi_*.so` was first removed / hidden / renamed.
So the package is now self-contained.  
This is still in a branch, and I recommend you first check it while keeping the branch.  Let's discuss if we want to keep things this way -- but at least it provides a neat little existence proof.

Feature/try rpath 

---

R/RcppExports.R
R/getTicks.R
src/RcppExports.cpp
src/getTicks.cpp

Updated getTicks to support condition code overwrite through a bool toggle, default is `FALSE`.
Multiple field types supported i.e. `eventType = c("TRADE","BEST_ASK","BEST_BID")`. Default is `TRADE`, output in long format.
e.g. `getTicks(con, "XUA Index", eventType = c("BEST_ASK", "BEST_BID"), startDateTime = as.POSIXct("2015-07-07 10:00"), endDateTime = as.POSIXct("2015-07-07 12:00"), setCondCodes = TRUE)`
Doc is updated in getTicks.R

Updated getTicks - Condition codes and multiple fields/event types

---

R/getTicks.R

Pending more testing against live data, thanks to @joshuaulrich for the follow-up yesterday.  
I'll follow up here if once I hear from the colleague you spotted the "infelicity" in the first place.

unique-ify timestamps before merge of multiple ticks (closes #76)

---

.Rbuildignore
.gitignore
ChangeLog
R/getTicks.R
cleanup
configure
src/Makevars.win

via configure (OS X, Linux) and src/Makevars.win
tested successfully on Windows and Linux
adjusted .gitignore, .Rbuildignore and cleanup accordingly
one additional tweak for getTicks.R: call zoo::index explicitly

cache Bbg header and library (closes #65)

---

ChangeLog
DESCRIPTION
R/RcppExports.R
R/beqs.R
man/beqs.Rd
src/RcppExports.cpp
src/beqs.cpp

Please take a look as time permits.   
This is similar to what @armstrtw does with `LazyFrame` but more direct / brutish:  we do one pass over the (first) data type, allocate and assign typed Rcpp vector accordingly and then do loop over the data and do the switcheroo on type.
So far only `character` and `float64` tested.  Adding `Date(time)` should be straightforward. 
Ohh, and I never have to say `SEXP` or `PROTECT`  :)

reworked beqs()

---

R/bdh.R

The BDH() example for an options field doesn't work as per the manual:
```
>opt <- c("periodicityAdjustment"="MONTHLY")
>bdh("SPY US Equity", c("PX_LAST", "VOLUME"),  start.date=Sys.Date()-31*6, options=opt)
Error: Enumeration type could not be found for MONTHLY
```
The correct override name is **opt <- c("periodicitySelection"="MONTHLY")**
```
>opt <- c("periodicitySelection"="MONTHLY")
>bdh("SPY US Equity", c("PX_LAST", "VOLUME"),  start.date=Sys.Date()-31*6, options=opt)
date PX_LAST    VOLUME
1  2015-10-16  203.27 114580052
2  2015-10-19  203.37  76523897
```

Update bdh.R Example

---

configure

added method='libcurl' in the download.file as it wasn't working.

fix download.file call for OSX build

---

src/bdp.cpp

simple string compare to check that the order of the results vector matches what we expect.  the new code uses seqNumber from bbg to determine the row number in the results vector.  This check just insures that the seqNumber matches the proper position in the securities argument.

add check for results vector matching order of securities vector

---

src/bds.cpp
src/blpapi_utils.cpp
src/blpapi_utils.h
src/subscribe.cpp

given how poor bbg data integrity is, I think we need these checks in place.

add sanity checks for bbgDateToJulianDate

---

ChangeLog
R/getTicks.R
man/getMultipleTicks.Rd
man/getTicks.Rd

this changes `getMultiTicks()` to only support `data.frame` and `data.table` objects for the return
having `fts` / `xts` / `zoo` here made no sense as we have tick types and cond codes which are not numeric

added data.table support to getMultipleTicks

---

ChangeLog
R/converters.R
R/getBars.R
R/getTicks.R
inst/NEWS.Rd
inst/unitTests/runit.getTicks.R

This adds a first column to data.table exports with the POSIXct -- some plotting etc functions want that.  I also adds date and time as before which makes for good grouping.
So I am suggesting to every-so-slightly change the API, but only in what was already optional.  Good enough?

better (optional) data.table export

---

ChangeLog
DESCRIPTION
inst/NEWS.Rd
src/bds.cpp

This addresses the concern by Tomas Kalibera (see [here](https://github.com/kalibera/rprotect/tree/master/reports/Rblpapi)) and updates ChangeLog and NEWS.

Replace PROTECT with Shield<>

---

DESCRIPTION
src/subscribe.cpp

use index of the securities vector as the CorrelationID, however this change requires unsubscribe to be called upon user interrupt otherwise, we attempt to recycle CorrelationID's upon the next subscription.

Fix subscribe

---

inst/unitTests/runit.bdp.R
src/bds.cpp
src/blpapi_utils.cpp

Fix a bug introduced by PR #273 
See the comments in PR #278 
```r
library(Rblpapi)
blpConnect()
out <- bdp(securities = c("BBG006YQMFQ5", "BBG005CMJQ71"),
fields = c("ISSUE_DT"))
out$ISSUE_DT
```

initialize DateVector() with NAs

---

DESCRIPTION
src/bds.cpp
src/blpapi_utils.cpp
src/getFieldInfo.cpp

Hi @eddelbuettel , first of all, thanks for making this great package. 
Occasionally, we need to return non-English characters from Bloomberg (as the example below). However, because the current version doesn't mark the encoding as UTF8 explicitly, it causes trouble on a Windows machine, where the native encoding varies.
This PR will fix this. I have manually compiled the PR version and tested it on the Bloomberg computer in the office and find no problems by far. 
If there's more need to be done, please let me know.
Thanks.
```r
library(Rblpapi)
blpConnect()
out <- bdp(securities = c("BBG006YQMFQ5", "BBG005CMJQ71"),
fields = c("NAME_CHINESE_SIMPLIFIED", "ISSUE_DT"),
overrides = c("SECURITY_NAME_LANG" = "10"))
Encoding(out$NAME_CHINESE_SIMPLIFIED)
out$ISSUE_DT
out$NAME_CHINESE_SIMPLIFIED …
```

Need to mark the string returned as UTF-8

---

ChangeLog
cleanup
configure

This PR addresses two nags from `R CMD check` which some time ago started to complain about use of `bash`.  
No package functionality is changed.

Remove bashisms by converting configure and cleanup (fixes: #324)

---

vignettes/rblpapi-intro.Rmd

This very simple PR switches the vignette to the very lightweight yet very legible 'water' CSS framework via `minidown`.

switch vignette to the minidown water framework (closes: #329)

---

R/bds.R
man/bds.Rd

As function `bds` accepts only one security and one field, the result should always be a single data.frame

Minor change to doc of bds - result is a data.frame

---

ChangeLog
DESCRIPTION
R/subscribe.R
README.md
inst/NEWS.Rd
man/subscribe.Rd

This PR finalises the changes for a new release to address #328, and finishes up the work in PRs #331 and #332 by updating the NEWS.Rd and ChangeLog files.  Otherwise the only other check is a another `R CMD check` warning on outdated http URLs which is fixed in the README.md and one manual page.
This could probably get shipped as is, but give that @johnlaing  found one minor blunder each in the two preceding PRs I may as well procede slowly :)

New release 0.3.11 (closes: #328)

---

ChangeLog
R/bdh.R
inst/tinytest/test_bdh.R
man/bdh.Rd

This picks up the nice work by @mtkerbeR in #334 but places it cleanly off the head of our repo.  It also add a ChangeLog entry and updated the Rd page.
Original motivation from #334 follows.
A first proposal of minor changes to code for function `bdh()` to return different types of objects - analogously to `getTicks()`
As this is one of my first contributions in R, please let me know about feedback/weaknesses of the proposed solutions, which I would be happy to take care of:
Two points worth mentioning:
1. a new Option `bdhType` is introduced, to allow for backward-compatibility.  Alternative would be to use `blpType` here as in getBars, however, if this value is set to a format which is not supported in bdh (like `matrix`, which is feasible in `getBars`) existing code might break. This …

returnAs=... support for bdh (closes #206) (rebased)

---

ChangeLog
DESCRIPTION
inst/tinytest/test_bdh.R

This adds the test refinement suggested by @mtkerbeR (whom I can't formally invite to code review, please just glance and nod if you have a minute) and rolls the version to mark it as distinct from the recent CRAN release.

Refine test and roll version to 0.3.11.1

---

src/bdh.cpp

Fixes #348.
In addition to stopping execution, we can capture the message and display it (via `verbose=TRUE`)
```
RequestFailure = {
reason = {
source = "Session"
category = "TIMEOUT"
errorCode = -1
description = "Request timed out at backend"
}
}
Error in bdh_Impl(con, securities, fields, start.date, end.date, options,  :
Bloomberg request timed out on server side
```

catch REQUEST_STATUS event type per #348

---

DESCRIPTION
vignettes/rblpapi-intro.md
vignettes/water.css

This PR suggests to follow a practice I just introduced in six of my own packages to replace use of packages `knitr`, `rmarkdown` and (for the CSS formatting) `minidown` (which taken together have a bit of footprint) with the _much simpler_ new package `simplermarkdown` which only needs one other package (for JSON) (plus a tiny CSS file) and wraps `pandoc` directly.  See the reverse suggests of [simplermarkdown](https://cloud.r-project.org/package=simplermarkdown) for examples.
Our vignette only used `pandoc` for code formatting and actually ran no R code (which is not uncommon) so the switch was trivial.  I put a locally rendered html version of the vignette [here](https://dirk.eddelbuettel.com/tmp/rblpapi-intro.html) if you want to peruse it. 
As for motivation, I find this (done via …

Switch from knitr+rmarkdown+minidown to simplermarkdown

---

ChangeLog
inst/tinytest/test_bds.R

As discussed in #351 :
Adds a file to test return type of function `bds`. 
Note that this checks for the behaviour as of 0.3.11, i.e. bds returning a list whose first element is a data.frame

Add test_bds.R

---

ChangeLog
DESCRIPTION
configure

This supercedes the PR in #360 
It has been tested at RHub -- links will last a few days as usual:
- [Windows, R-devel](https://builder.r-hub.io/status/Rblpapi_0.3.13.1.tar.gz-6637bc5a002946fd90a3524fc6f89f3c)
- [Fedora, R-devel](https://builder.r-hub.io/status/Rblpapi_0.3.13.1.tar.gz-c6f29ce7e4fa42b2913432373dfdbe2c)
- [Ubuntu, R-release](https://builder.r-hub.io/status/Rblpapi_0.3.13.1.tar.gz-c3da2a808c234484a1bdbe0e68e80d88)
As usage example was already provided [in this comment](https://github.com/Rblp/Rblpapi/pull/360#issuecomment-1046915361)

Generalize configure for optional use of local library and header archives

---

ChangeLog
DESCRIPTION
configure
src/Makevars.in

CRAN came knocking because our package is one of the remaining ones (the other is, <cough, cough> mine too ...) requiring to set `StagedInstall: no` in `DESCRIPTION`.  This goes _way_ back to when @jeroen helped us get to the package CRAN-ready and has to do with the fact that we (at the time) opted for _absolute_ paths via `@rpath` instructions to the dynamic linker.
Well turns out relative ones work too, and @kalibera was of excellent assistance here so this now works.  I also sent it to RHub's macOS test instance (that use the CRAN setup, not the one using `brew`) and it passed too.  This needed changes to no longer `Suggests:` on the now-departed `fts` package, I will send those in subsequent PR.

No longer enforce staged install

---

ChangeLog
DESCRIPTION
R/bdh.R
R/blpAuthenticate.R
R/getBars.R
R/getTicks.R
inst/tinytest/test_bdh.R
man/bdh.Rd
man/getBars.Rd
man/getTicks.Rd
src/RcppExports.cpp

This PR removes reference to the (always optional) package `fts` which is no longer on CRAN.
It is probably best to first merge #373 and to then rebase, but the two reviews can happen concurrently.

Remove (optional) use of fts package now in package heaven

---

.github/workflows/ci.yaml
ChangeLog

Some minor maintenance I have been doing to a number of my other repos.  I find the 'versioned' schema of the actions quite silly as we are forced to increment it every few years.  Oh well.  Still a free service that works well.

Update GitHub Actions to actions/checkout@v4 and r-ci-setup

---

.editorconfig
src/Makevars.in
src/authenticate.cpp
src/bdh.cpp
src/bdp.cpp
src/bds.cpp
src/beqs.cpp
src/blpapi_utils.cpp
src/bsrch.cpp
src/fieldsearch.cpp
src/getBars.cpp
src/getTicks.cpp
src/lookup.cpp

Also removes now-outdated hard-wiring of C++11 as a compilation standard and adds an .editorconfig file.
The library update (via an update to the blp repo) will follow.

Avoid deprecation warnings over char* instead of Name

---

.Rbuildignore
ChangeLog
DESCRIPTION
README.md

This PR regroups a few cleanups such as
- increment the version to indicate change from last release
- switch to Authors@R which CRAN now requires, if you have [ORCID IDs](https://orcid.org/) we can add them
- switch the CI badge to the CI we actually use
- minor .Rbuildignore update
Nothing critical but all _en route_ to updating the API libraries which is pending.

Package maintenance: DESCRIPTION, README, .Rbuildignore updates

---

src/bds.cpp

As identified by @mtkerbeR in #393, there was a `Name{}` invocation too many which bricked `bds()`.  This restores it.
Many thanks to @mtkerbeR for catching this and the patient testing.

Correct request formation as identified in #393

---

.github/workflows/ci.yaml
ChangeLog
DESCRIPTION
configure
src/Makevars.in
src/Makevars.win

This PR switches to release 3.24.6.1 of the Bloomberg API, and enables arm64 builds for macOS.
We attempted to resurrect x86_64 builds for macOS.  As the current release of the Bloomberg API supports only arm64 on macOS, we retain the previouse.  And while that built fine previously it somehow now fails (at r-universe) for that platform.  It may hence also fail at CRAN for macOS x86_64.  We would need to rely on someone with that platform to debug more locally.
After approving please **do not merge immediately** but allow me to do so also in preparation of a next release.

Use release 3.24.6.1

---

ChangeLog
src/bdp.cpp

When doing a bdp request, we can receive an error message (quota ...)
in the result which gives the following error message:
_Choice sub-element not found for name 'securityData'._
Log the received message and throw an exception to have a clearer error message.

Quota error handling on bdp request

---

ChangeLog
DESCRIPTION
R/init.R
configure
src/Makevars.in
src/authenticate.cpp
src/bdh.cpp
src/bdp.cpp
src/bds.cpp
src/beqs.cpp
src/blpConnect.cpp
src/blpVersion.cpp
src/blpapi_utils.cpp
src/bsrch.cpp
src/fieldsearch.cpp
src/getBars.cpp
src/getFieldInfo.cpp
src/getTicks.cpp
src/lookup.cpp
src/subscribe.cpp

Fixes #405 
This addresses the issue described in #405.  We now (on Unix and alike, windows is as usual separate) only attempt to download on the two known-good setups: amd64 on linux, and arm64 on macos.  Other combinations such as the (on life-support at CRAN) older amd64 on macOS will build with `#define` indicating lack of blp support.  All exported files now have an empty fallback and just return NULL or an empty list or data.frame.  The startup message reflects this too.
No actual working configuration is changed in any way.

Make build more robust to absence of viable blp library and headers

---

ChangeLog
src/authenticate.cpp
src/bdh.cpp
src/bdp.cpp
src/bds.cpp
src/beqs.cpp
src/blpConnect.cpp
src/blpVersion.cpp
src/bsrch.cpp
src/fieldsearch.cpp
src/getBars.cpp
src/getFieldInfo.cpp
src/getTicks.cpp
src/lookup.cpp
src/subscribe.cpp

remove Rcpp::export tags on lightweight function defs

---

R/RcppExports.R
R/blpConnect.R
man/blpConnect.Rd
src/RcppExports.cpp
src/blpConnect.cpp

See https://developer.bloomberg.com/portal/products/desktop_api?chapterId=4551&entityType=document#getting_started_with_desktop_api-app_registration
Seems similar to appName for B-PIPE, so just took inspiration from that.

add appIdentityKey optional argument to blpConnect()
