Rblp/Rblpapi

DESCRIPTION, src/getTicks.cpp
and forgot to pull so another commit on merging
=> also correct getTicks

R/getBars.R, R/getTicks.R, man/getBars.Rd, man/getTicks.Rd
that was just a fat finger I had not noticed before
=> fix trivial Rd typo

R/bdp.R, man/bdp.Rd
=> it is 'ESA Index' not 'ESA Comdty'

DESCRIPTION, R/blpConnect.R, R/init.R, R/zzz.R, man/bds.Rd, man/blpConnect.Rd
not to be to too stubborn but I think we should reserve 0.3.0 for a "bigger" change
obviously Whit's call so feel free to close if 0.3.0 was the desired number
=> set version to 0.2.3

.travis.yml
this is minor; I was hoping for a bit of a speedup but in the one run so far it wasn't material yet
will not hurt though, and does not overlap with the other PR
=> install BH from Michael's c2d4u, move ppa setting up for one less apt-get update

DESCRIPTION, src/Makevars.win
this lets us build on Windows using the external tarballs
=> updated Windows build

R/bdh.R, R/bdp.R, R/bds.R, R/blpAuthenticate.R, R/blpConnect.R, R/blpDisconnect.R, R/defaultConnection.R, R/fieldSearch.R, R/getBars.R, R/getTicks.R, R/init.R, configure, src/Makevars.in, src/Makevars.win
Bunch of copyright headers added
=> copyright headers

src/blpapi_utils.cpp
=> fix auto_ptr warning

ChangeLog, src/beqs.cpp
This makes `beqs()` mostly usable.
=> Feature/beqs improvements -- should close #80

ChangeLog, R/beqs.R, man/beqs.Rd
Apparently I never merged this.
=> correct date use in beqs() example (closes #85)

ChangeLog, src/beqs.cpp
gotta love compiler warnings. so that was a non-test all along...
and for fuck's sake why does my laptop insist that all whitespace changed -- maybe I need to add something [along these lines](http://stackoverflow.com/a/5834094/143305)
=> important little fix on comparison

src/RcppExports.cpp, src/bdp.cpp, src/blpapi_utils.cpp, src/getFieldInfo.cpp, src/getFieldInfo.h
refactor bdp using FieldInfoRequest results.
=> Use fieldinfo for bdp

src/RcppExports.cpp, src/bdh.cpp, src/getFieldInfo.cpp, src/getFieldInfo.h
will circle back after and clean up some of the utils code.
=> Use fieldinfo for bdh

inst/unitTests/runit.bdh.R, inst/unitTests/runit.bdp.R, src/bdh.cpp, src/bdp.cpp, src/bds.cpp, src/blpapi_utils.cpp, src/blpapi_utils.h
removed the .setup function from those tests.
=> Update populate df row

src/blpapi_utils.cpp
more clean if/else for fix. #107
=> add missing terminal condition in case DatatypeT::Datetime

inst/unitTests/runit.bdh.R, src/blpapi_utils.cpp, src/blpapi_utils.h
=> Fix date passed as double

ChangeLog, NAMESPACE, inst/NEWS.Rd, src/init.c
This is pretty innocent and something we needed to do anyway for the next upload as per discussions on the lists and changes in R-devel (which will soon enough be R 3.4.0).  I used its tool to create the `init.c` file.
=> added R_registerRoutines() and R_useDynamicSymbols

ChangeLog, src/bds.cpp, src/blpapi_utils.cpp, src/finalizers.h
Nothing really earth shattering here but we're now free of PROTECT throughout
=> Additional minor updates

.travis.yml, ChangeLog, DESCRIPTION, R/getTicks.R, R/lookup.R, inst/NEWS.Rd, man/getBars.Rd, man/getTicks.Rd, man/lookupSecurity.Rd
documents 140 day limit
adds symbol regexp example to lookupSecurity
updates Travis to use Ubuntu 'trusty'
=> Small updates

R/blpAuthenticate.R, R/blpConnect.R
Some pointers to how to use blpAuthenticate.
=> Blp auth documentation

R/bdh.R, man/bdh.Rd, src/bdh.cpp
fixes #268 
includes new example
=> accomodate extra field from relative date option to bdh

ChangeLog, src/Rblpapi_types.h, src/bds.cpp
=> Fix BDS segfault 

R/lookup.R
=> warn for maxResults > 1000

R/bsrch.R, man/bsrch.Rd, src/bsrch.cpp
=> Correct request formation, add working example
